name: hadisaaji
description: "Hadiths du Prophète Muhammad ﷺ traduits en Pulaar"
publish_to: 'none'
version: 1.0.3+5

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  shared_preferences: ^2.3.4
  share_plus: ^10.1.4
  flutter_local_notifications: ^18.0.1
  provider: ^6.1.2
  audioplayers: ^6.1.0
  supabase_flutter: ^2.8.0
  flutter_timezone: ^3.0.1
  timezone: ^0.10.1
  url_launcher: ^6.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/app_icon_1024.png"
  adaptive_icon_background: "#0D7C66"
  adaptive_icon_foreground: "assets/images/app_icon_1024.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
